name: money_management_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^8.8.1
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.3
  modal_progress_hud: ^0.1.3
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/CM Sans Serif.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
